# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing_profiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_On_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(auto_now_add=True)),
                ('updation_date', models.DateField(auto_now_add=True)),
                ('content', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='add_on_instance',
            name='add_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddOns.AddOn'),
        ),
        migrations.AddField(
            model_name='add_on_instance',
            name='marketing_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_addon', to='marketing_profiles.Marketing_Profile'),
        ),
    ]
