# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddOns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_on_instance',
            name='invoice_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
