# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-17 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddOns', '0002_add_on_instance_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_on_instance',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='add_on_instance',
            name='registration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addon',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addon',
            name='registration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addon',
            name='updation_date',
            field=models.DateField(),
        ),
    ]
