# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddOns', '0003_auto_20190317_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_on_instance',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
