# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 12:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_username', models.CharField(max_length=100)),
                ('profile_password', models.CharField(max_length=120)),
                ('trial', models.CharField(default=True, max_length=20)),
                ('total', models.DecimalField(decimal_places=1, max_digits=3)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(auto_now_add=True)),
                ('targeting_audience', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('invoice_id', models.CharField(max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
