# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-17 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
