# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190317_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default=' ', max_length=120, null=True),
        ),
    ]
