# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_activation',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
